#!/usr/bin/env python3
import os
import subprocess
import sys

def main():
    # Files generated by ruler apply for Claude Code and Cursor agents respectively
    output_files = ["CLAUDE.md", "AGENTS.md"]

    # 1. Remove existing output files
    for filepath in output_files:
        if os.path.exists(filepath):
            try:
                os.remove(filepath)
                print(f"Removed existing {filepath}")
            except Exception as e:
                print(f"Failed to remove {filepath}: {e}")
                sys.exit(1)

    # 2. Run ruler apply
    print("Running npx --yes @intellectronica/ruler apply...")
    try:
        subprocess.run(["npx", "--yes", "@intellectronica/ruler", "apply"], check=True)
    except subprocess.CalledProcessError as e:
        print(f"ruler apply failed: {e}")
        sys.exit(1)

    # 3. Remove metadata lines containing "Source: .ruler/"
    # If file paths are described, AI agents may mistakenly treat them as references and attempt unnecessary reads.
    for filepath in output_files:
        if os.path.exists(filepath):
            print(f"Removing 'Source: .ruler/' lines from {filepath}...")
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    lines = f.readlines()

                with open(filepath, "w", encoding="utf-8") as f:
                    for line in lines:
                        if not line.strip().startswith("Source: .ruler/"):
                            f.write(line)
                print(f"Successfully processed {filepath}")
            except Exception as e:
                print(f"Failed to process {filepath}: {e}")
                sys.exit(1)

    # 4. Format as Markdown (run prettier)
    for filepath in output_files:
        if os.path.exists(filepath):
            print(f"Formatting {filepath} with prettier...")
            try:
                # Trim leading and trailing whitespace/newlines
                with open(filepath, "r", encoding="utf-8") as f:
                    content = f.read().strip()
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(content + "\n")

                # Format with prettier
                subprocess.run(["npx", "--yes", "prettier", "--write", filepath], check=True)
                print(f"Successfully formatted {filepath}")
            except subprocess.CalledProcessError as e:
                print(f"prettier formatting failed: {e}")
                sys.exit(1)
            except Exception as e:
                print(f"Failed to clean up {filepath}: {e}")
                sys.exit(1)
        else:
            print(f"Warning: {filepath} not found for formatting.")

if __name__ == "__main__":
    main()
